# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-03 07:18
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_auto_20171103_0715'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
